[pytest]
testpaths = tests
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:builtin type Swig.*:DeprecationWarning
    ignore:builtin type swigvarlink.*:DeprecationWarning
    ignore:The 'strip_cdata' option:DeprecationWarning
